#ifndef FFI_H
#define FFI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void ffi_setup(void);

double ffi_bmp180(void);

double ffi_sr04(void);

void ffi_blink(void);

#endif
